spring:
  application:
    name: leaderboard-service

server:
  port: 8080

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public

  jpa:
    hibernate:
      ddl-auto: validate

      show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

flyway:
  enabled: true
  location: classpath:db/migration
  baseline-on-migrate: true
  clean-disabled: true
  url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
  password: ${POSTGRES_PASSWORD}
  user: ${POSTGRES_USER}

yellow-dot:
  base-url: ${YELLOW-DOT_BASE_URL}
  api-key: ${YELLOW-DOT_API_KEY}

integration:
  shared-secret: ${INTEGRATION_SHARED_SECRET}